=== YArzumanyan/data-factory/pipeline_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Pipeline Schema",
    "description": "A schema to validate the structure of a pipeline definition.",
    "type": "object",
    "properties": {
        "title": {
            "description": "The main title of the pipeline.",
            "type": "string"
        },
        "description": {
            "description": "A brief description of what the pipeline does.",
            "type": "string"
        },
        "variables": {
            "description": "A list of data variables used or produced within the pipeline.",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "description": "A unique identifier for the variable within the pipeline.",
                        "type": "string"
                    },
                    "title": {
                        "description": "A human-readable title for the variable.",
                        "type": "string"
                    },
                    "datasetUuid": {
                        "description": "The UUID of an existing dataset associated with this variable.",
                        "type": "string",
                        "format": "uuid"
                    }
                },
                "required": [
                    "id",
                    "title"
                ]
            }
        },
        "steps": {
            "description": "The sequence of steps or processes in the pipeline.",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "description": "A unique identifier for the step within the pipeline.",
                        "type": "string"
                    },
                    "title": {
                        "description": "A human-readable title for the step.",
                        "type": "string"
                    },
                    "pluginUuid": {
                        "description": "The UUID of the plugin that executes this step.",
                        "type": "string",
                        "format": "uuid"
                    },
                    "inputs": {
                        "description": "A list of variable IDs that are inputs to this step.",
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "outputs": {
                        "description": "A list of variable IDs that are outputs from this step.",
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "precededBy": {
                        "description": "A list of step IDs that must be completed before this step can run.",
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "required": [
                    "id",
                    "title",
                    "pluginUuid",
                    "inputs",
                    "outputs"
                ]
            }
        }
    },
    "required": [
        "title",
        "description",
        "variables",
        "steps"
    ]
}

=== YArzumanyan/data-factory/test_pipeline.json
{
  "title": "Validation & Cleansing Pipeline v3",
  "description": "This pipeline validates raw input data and cleanses it to produce a final output.",
  "variables": [
    {
      "id": "raw-data-var",
      "title": "Initial Raw Input",
      "datasetUuid": "28b768b7-4e1e-4196-8c30-6a83809cea93"
    },
    {
      "id": "validated-data-var",
      "title": "Intermediate Validated Data"
    },
    {
      "id": "cleansed-output-var",
      "title": "Final Cleansed Output Var"
    }
  ],
  "steps": [
    {
      "id": "validate-step",
      "title": "Validate Raw",
      "pluginUuid": "97780dca-887c-41b6-94e6-494566c303fc",
      "inputs":  ["raw-data-var"],
      "outputs": ["validated-data-var"]
    },
    {
      "id": "cleanse-step",
      "title": "Cleanse Data",
      "pluginUuid": "f5856e3e-80a0-4e02-b8c6-90bd4077e022",
      "inputs": ["validated-data-var"],
      "outputs": ["cleansed-output-var"],
      "precededBy": ["validate-step"]
    }
  ]
}

=== YArzumanyan/data-factory/manager-cli/example/pipeline_dependant.json
{
  "title": "Article processing",
  "description": "This pipeline processes articles by validating and reversing the data.",
  "variables": [
    {
      "id": "article-var",
      "title": "Article Raw Input",
      "datasetUuid": "629e0906-9b1b-4cd8-b11c-dab62aff1bc5"
    },
    {
      "id": "p2-final-var",
      "title": "Final Reversed Output Var"
    }
  ],
  "steps": [
    {
      "id": "validate-step",
      "title": "Validate Raw",
      "pluginUuid": "63426768-0002-4ca8-925f-ff6ddcfa5a20",
      "inputs": [
        "article-var"
      ],
      "outputs": [
        "p2-final-var"
      ]
    }
  ]
}

=== YArzumanyan/data-factory/pipeline_template.json
{
  "title": "Validation & Cleansing Pipeline v3",
  "description": "This pipeline validates raw input data and cleanses it to produce a final output.",
  "variables": [
    {
      "id": "raw-data-var",
      "title": "Initial Raw Input",
      "datasetUuid": "DATASET_UUID"
    },
    {
      "id": "validated-data-var",
      "title": "Intermediate Validated Data"
    },
    {
      "id": "cleansed-output-var",
      "title": "Final Cleansed Output Var"
    }
  ],
  "steps": [
    {
      "id": "validate-step",
      "title": "Validate Raw",
      "pluginUuid": "PLUGIN_UUID",
      "inputs": [
        "raw-data-var"
      ],
      "outputs": [
        "validated-data-var"
      ]
    },
    {
      "id": "cleanse-step",
      "title": "Cleanse Data",
      "pluginUuid": "PLUGIN_UUID",
      "inputs": [
        "validated-data-var"
      ],
      "outputs": [
        "cleansed-output-var"
      ],
      "precededBy": [
        "validate-step"
      ]
    }
  ]
}

=== YArzumanyan/data-factory/manager-cli/example/pipeline_template.json
{
  "title": "Article processing",
  "description": "This pipeline processes articles by validating and reversing the data.",
  "variables": [
    {
      "id": "article-var",
      "title": "Article Raw Input",
      "datasetUuid": "DATASET_UUID"
    },
    {
      "id": "validated-data-var",
      "title": "Intermediate Validated Data"
    },
    {
      "id": "reversed-output-var",
      "title": "Final Reversed Output Var"
    }
  ],
  "steps": [
    {
      "id": "validate-step",
      "title": "Validate Raw",
      "pluginUuid": "PLUGIN_UUID",
      "inputs": [
        "article-var"
      ],
      "outputs": [
        "validated-data-var"
      ]
    },
    {
      "id": "reverse-step",
      "title": "Reverse Data",
      "pluginUuid": "PLUGIN_UUID",
      "inputs": [
        "validated-data-var"
      ],
      "outputs": [
        "reversed-output-var"
      ],
      "precededBy": [
        "validate-step"
      ]
    }
  ]
}

=== YArzumanyan/data-factory/dependant_pipeline_template.json
{
  "title": "Dependant Pipeline",
  "description": "This pipeline uses the output from a previous pipeline to produce a final output.",
  "variables": [
    {
      "id": "pipe-output",
      "title": "Output from Previous Pipeline",
      "datasetUuid": "DEPENDATNT_DATASET_UUID"
    },
    {
      "id": "used-data-var",
      "title": "Final Output"
    }
  ],
  "steps": [
    {
      "id": "use-dataset",
      "title": "Use Data",
      "pluginUuid": "PLUGIN_UUID",
      "inputs": [
        "pipe-output"
      ],
      "outputs": [
        "cleansed-output-var"
      ]
    }
  ]
}
